const root = document.getElementById('bingo-fncs');
let viewedCardId = '', viewerOpen = false;
let selected = new Set(), champion = '', latest = null, currentUser = null, renderedVersion = '';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
window.renderBingoFncs = function(data,user){
 latest=data;currentUser=user;if(!root)return;
 const version=JSON.stringify([data?.open,data?.firstRound,data?.autoEntry,data?.objectives,data?.cards,user?.id]);
 if(version===renderedVersion)return;
 const pageScroll=window.scrollY, innerScroll=root.scrollTop;
 renderedVersion=version;
 root.replaceChildren();if(!data){root.append(el('p','Bingo FNCS: à espera da primeira publicação.'));return;}
 root.append(el('h2','Bingo FNCS · 300 pontos'),el('p',data.open?'Escolhe campeão, duas médias e uma fácil. Resgata Bingo FNCS e envia os códigos no chat.':'Inscrições fechadas. Podes consultar os objetivos e cartões.'));
 if(data.autoEntry)root.append(el('p','Entrada automática: até 9 duplas terminadas no Tracker conta a partida atual; a partir de 10, a seguinte. Sem leitura recente, a entrada passa para a próxima partida. As inscrições terminam às 10 duplas terminadas no jogo 5 do dia 2.'));
 root.append(el('p',`Cartão 4 × 4 · mínimo 8 duplas · válido a partir do jogo ${data.firstRound}. A confirmação no chat volta a verificar a disponibilidade.`));
 const select=el('select');select.setAttribute('aria-label','Dupla campeã');select.append(new Option('Escolher campeão',''));for(const c of data.champions)select.append(new Option(c.teamName,c.code));select.value=champion;select.onchange=()=>{champion=select.value;update();};root.append(select);
 const command=el('input');command.readOnly=true;command.setAttribute('aria-label','Comando para o chat');command.style.width='100%';command.style.fontSize='18px';command.onclick=()=>{command.focus();command.select();command.setSelectionRange(0,command.value.length);};const copy=el('button','Copiar comando');copy.onclick=async()=>{try{await navigator.clipboard.writeText(command.value);copy.textContent='Copiado — cola no chat';}catch{command.focus();command.select();command.setSelectionRange(0,command.value.length);let copied=false;try{copied=document.execCommand('copy');}catch{}copy.textContent=copied?'Copiado — cola no chat':'Seleciona e copia o comando abaixo';hint.textContent=copied?'Agora cola o comando no chat da Twitch.':'No telemóvel, mantém o dedo no comando e escolhe Copiar. No computador, usa Ctrl+C.';}};
 const hint=el('p');root.append(command,copy,hint);
 const compatibleChoice = (cells,c) => !cells.some(x=>x.code===c.code||x.teamKey===c.teamKey&&x.kind===c.kind) && c.playerIds.every(id=>cells.filter(x=>x.playerIds.includes(id)).length<3);
 const selectedCells = () => [...(data.champions.find(c=>c.code===champion)?[data.champions.find(c=>c.code===champion)]:[]),...[...selected].map(code=>data.objectives.find(c=>c.code===code)).filter(Boolean)];
 const list=el('div');list.className='bingo-options';const choices=[];
 const group=c=>!c.available?2:c.difficulty==='hard'?1:0;
 const ordered=[...data.objectives].sort((a,b)=>group(a)-group(b));
 let previousGroup=-1;
 for(const c of ordered){const currentGroup=group(c);if(currentGroup!==previousGroup){const heading=el('h3',currentGroup===0?'Disponíveis para escolher':currentGroup===1?'Difíceis · sorteadas pelo sistema':'Indisponíveis · arquivo');heading.style.gridColumn='1 / -1';list.append(heading);previousGroup=currentGroup;}const label=el('label');const check=el('input');check.type='checkbox';check.checked=selected.has(c.code);check.disabled=(!c.available&&!check.checked)||c.difficulty==='hard';choices.push({check,cell:c});check.onchange=()=>{if(check.checked){const limit=c.difficulty==='easy'?1:c.difficulty==='medium'?2:0;const count=[...selected].filter(code=>latest.objectives.find(x=>x.code===code)?.difficulty===c.difficulty).length;if(count<limit&&compatibleChoice(selectedCells(),c))selected.add(c.code);else check.checked=false;}else selected.delete(c.code);update();};label.append(check,el('strong',`${c.code} · ${c.teamName} · ${c.label}${c.kind==='single'?' numa partida':''}`),el('small',`Dificuldade: ${{easy:'fácil',medium:'média',hard:'difícil · sorteada'}[c.difficulty]} — ${c.available?(c.origin==='historical'||String(c.evidence).includes('/8 jogos')?'Referência do torneio anterior: ':'Base: ')+c.evidence:(c.reason==='Já cumprido'&&c.kind==='single'?'Já aconteceu numa partida deste campeonato':c.reason)}`));if(c.progress)label.append(el('small',c.progress.text+' · faltam '+c.progress.remaining));list.append(label);}root.append(list);
 function update(){for(const {check,cell} of choices){const count=[...selected].filter(code=>latest.objectives.find(x=>x.code===code)?.difficulty===cell.difficulty).length;const limit=cell.difficulty==='easy'?1:cell.difficulty==='medium'?2:0;check.disabled=!check.checked&&(!cell.available||count>=limit||!compatibleChoice(selectedCells().filter(c=>c.code!==cell.code),cell));check.closest('label').style.opacity=check.disabled?'0.5':'1';}const cs=[...selected].map(code=>latest.objectives.find(c=>c.code===code));const compatible=selectedCells().every((c,i,all)=>compatibleChoice(all.slice(0,i),c));const valid=compatible&&!!champion&&cs.length===3&&cs.every(c=>c?.available)&&cs.filter(c=>c.difficulty==='easy').length===1&&cs.filter(c=>c.difficulty==='medium').length===2;command.value=valid?`!bingo ${champion} ${[...selected].join(' ')}`.trim():'';command.placeholder=valid?'':'Completa quatro escolhas compatíveis para gerar o comando';copy.disabled=!valid;hint.textContent=!compatible?'Estas escolhas repetem objetivos da mesma família para a mesma dupla, ou excedem 3 casas por jogador. Desmarca uma opção.':valid?(data.open?'Copia o comando e cola no chat depois de resgatar Bingo FNCS.':'Já podes copiar o comando. Aguarda a abertura das inscrições para resgatar e enviar no chat.'):`Falta selecionar: ${!champion?'dupla campeã; ':''}1 fácil e 2 médias. Selecionadas: ${cs.filter(c=>c?.difficulty==='easy').length} fácil / ${cs.filter(c=>c?.difficulty==='medium').length} médias. As difíceis são sorteadas.`;}
 update();const cardArea=el('section');cardArea.className='bingo-my-card';cardArea.append(el('h3','O meu cartão'));
 const card=user?data.cards.find(c=>c.userId===String(user.id)):null;
 if(!user)cardArea.append(el('p','Entra com a Twitch no site para encontrares o teu cartão.'));
 else if(!card)cardArea.append(el('p','Já resgataste? Envia no chat o comando copiado acima para confirmar o cartão. Depois aguarda a atualização do site.'));
 else cardArea.append(cardContents(card));
 function cardContents(c){const content=el('div');content.append(el('p',c.name+' · '+c.completed+'/16 casas · '+c.lines+' linhas'),el('p','Válido a partir da partida '+c.firstRound));const scroll=el('div');scroll.className='bingo-card-scroll';scroll.tabIndex=0;scroll.setAttribute('aria-label','Cartão de '+c.name);const grid=el('div');grid.className='bingo-grid';for(const cellData of c.cells){const cell=el('div');cell.className=cellData.proof?'done':'';cell.append(el('strong',cellData.teamName),el('span',cellData.label),el('b',cellData.proof?'✓':''));if(cellData.progress)cell.append(el('small',cellData.progress.text));if(cellData.proof?.sessionId){const a=el('a','Ver resultado');a.href='https://fortnitetracker.com/events/sessions/'+cellData.proof.sessionId;a.target='_blank';a.rel='noreferrer';cell.append(a);}grid.append(cell);}scroll.append(grid);content.append(scroll);return content;}

 root.prepend(cardArea);
 if(card){select.hidden=true;command.hidden=true;copy.hidden=true;hint.hidden=true;list.hidden=true;}
 const viewer=el('details');viewer.className='bingo-viewer';viewer.open=viewerOpen;viewer.append(el('summary','Ver cartões dos jogadores'));const picker=el('select');picker.setAttribute('aria-label','Escolher cartão de um jogador');picker.append(new Option('Escolher jogador',''));for(const c of [...data.cards].sort((a,b)=>a.name.localeCompare(b.name)))picker.append(new Option(c.name+' · '+c.completed+'/16',String(c.userId)));if(!data.cards.some(c=>String(c.userId)===viewedCardId))viewedCardId='';picker.value=viewedCardId;const preview=el('div');preview.setAttribute('aria-live','polite');const showCard=()=>{preview.replaceChildren();const c=data.cards.find(c=>String(c.userId)===viewedCardId);preview.append(c?cardContents(c):el('p',data.cards.length?'Escolhe um jogador para consultar o cartão.':'Ainda não há cartões confirmados.'));};picker.onchange=()=>{viewedCardId=picker.value;showCard();};viewer.ontoggle=()=>{if(viewer.isConnected)viewerOpen=viewer.open;};viewer.append(el('p','Consulta qualquer cartão, mesmo sem iniciar sessão. No telemóvel, desliza o cartão na horizontal para ver todas as casas.'),picker,preview);showCard();root.insertBefore(viewer,cardArea.nextSibling);
 root.append(el('h3','Classificação Bingo FNCS'));const ranking=el('ol');ranking.className='bingo-ranking';for(const c of [...data.cards].sort((a,b)=>b.completed-a.completed||b.lines-a.lines||a.name.localeCompare(b.name))){const item=el('li');const button=el('button','Ver cartão de '+c.name);button.type='button';button.onclick=()=>{viewedCardId=String(c.userId);picker.value=viewedCardId;viewerOpen=true;viewer.open=true;showCard();viewer.scrollIntoView({block:'start',behavior:'smooth'});};item.append(el('span',c.name+' — '+c.completed+'/16 · '+c.lines+' linhas'),button);ranking.append(item);}root.append(ranking);
 root.scrollTop=innerScroll;window.scrollTo({top:pageScroll,behavior:'instant'});
};
if(root?.dataset.local==='true'){const refresh=async()=>{try{const r=await fetch('http://127.0.0.1:3210/api/bingo-fncs/state');if(!r.ok)throw Error();window.renderBingoFncs(await r.json(),currentUser);}catch{root.replaceChildren(el('p','Liga o motor do jogo para consultar o bingo.'));}};refresh();setInterval(refresh,5000);}
